### ISSUE TITLE
ERROR - Invalid syntax in plugin file of plugin fixcbdfirmware

### ISSUE THREAD

**Issue by CatfoodOpener** [OctoPrint/OctoPrint-FixCBDFirmware#11]
Greetings,

I am having trouble with the plugin when rebooting.  It installs successfully from the plugin manager but when I reboot the PI, I get the following error.  I also seem to have a similar error in Octolapse so maybe something wrong with my system install.  I'm not very knowledgeable on linux so I don't know what this error is telling me.

2023-04-18 14:19:58,442 - octoprint.startup - INFO - ******************************************************************************
2023-04-18 14:19:58,449 - octoprint.startup - INFO - Starting OctoPrint 1.7.3
2023-04-18 14:19:58,450 - octoprint.startup - INFO - ******************************************************************************
2023-04-18 14:19:59,907 - octoprint.util.connectivity.connectivity_checker - INFO - Connectivity state is currently: online
2023-04-18 14:19:59,908 - octoprint.util.connectivity.connectivity_checker - INFO - Connecting to 1.1.1.1:53 is working
2023-04-18 14:19:59,911 - octoprint.util.connectivity.connectivity_checker - INFO - Resolving octoprint.org is working
2023-04-18 14:19:59,929 - octoprint.startup - INFO - Unable to fetch plugin blacklist from https://plugins.octoprint.org/blacklist.json, proceeding without it: HTTPSConnectionPool(host='plugins.octoprint.org', port=443): Max retries exceeded with url: /blacklist.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x74a65670>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2023-04-18 14:19:59,930 - octoprint.startup - INFO - Blacklist processing done
2023-04-18 14:20:00,005 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2023-04-18 14:20:02,548 - octoprint.plugin.core - ERROR - Invalid syntax in plugin file of plugin fixcbdfirmware
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 798, in _parse_metadata
    return parse_plugin_metadata(self.location)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 94, in parse_plugin_metadata
    root = ast.parse(f.read(), filename=path)
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_fixcbdfirmware/__init__.py", line 64
    self._logger.info(f"Replacing {orig} with {repl}")
                                                    ^
SyntaxError: invalid syntax
2023-04-18 14:20:03,239 - octoprint.plugin.core - ERROR - Error loading plugin octolapse
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 1291, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 68, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse/__init__.py", line 63, in <module>
    import octoprint_octolapse.camera as camera
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse/camera.py", line 42, in <module>
    from octoprint_octolapse.settings import CameraProfile, MjpgStreamerControl, MjpgStreamer
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse/settings.py", line 43, in <module>
    from collections.abc import Iterable
ImportError: No module named abc

**Comment by foosel** [comment]
`/home/pi/oprint/local/lib/python2.7` This looks like you are still running under Python 2.7. Neither [OctoPrint itself](https://octoprint.org/blog/2022/01/31/octoprint-1.8.0-will-require-python-3/) nor any of the plugins I personally maintain (like this one) supports Python 2 anymore, which has been EOL now since January 2020. That is over three years now. [Please update your OctoPrint installation to Python 3 already.](https://community.octoprint.org/t/upgrading-your-octoprint-install-to-python-3/)
